name: Update user-agent.json
on:
  schedule:
    - cron:  '0 0 1 * *'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2 
      - name: wget
        run: wget https://github.com/intoli/user-agents/raw/master/src/user-agents.json.gz
      - name: install gzip 
        run: sudo apt-get install gzip 
      - name: un-gzip
        run: gzip -d user-agents.json.gz
      - name: filter
        run: jq '[.[].userAgent]|unique' user-agents.json -r > user-agent.json
      - name: delete
        run: rm user-agents.json
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Update user-agents.json'
