name: Update user-agents.json
on:
  schedule:
    - cron:  '30 17 * * *'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2      
      - name: wget
        run: wget https://github.com/intoli/user-agents/raw/master/src/user-agents.json.gz
      - name: install gzip 
        run: sudo apt-get install gzip 
      - name: un-gzip
        run: gzip -d user-agents.json.gz
      - name: Add & Commit
        uses: EndBug/add-and-commit@v8.0.2
        with:
          author_name: VinaBot
          message: 'Update user-agents.json'
